### ISSUE TITLE
twitter-dashboard craps out if the rq db is cleared

### ISSUE THREAD

**Issue by vmtyler** [vmtyler/vascodagama#6]
Need to add some input checking 

```
2015-04-09T10:56:17.69-0400 [App/0]      ERR Traceback (most recent call last):
2015-04-09T10:56:17.69-0400 [App/0]      ERR   File "run_dashboard.py", line 6, in <module>
2015-04-09T10:56:17.69-0400 [App/0]      ERR     update_dashboard()
2015-04-09T10:56:17.69-0400 [App/0]      ERR   File "/home/vcap/app/dashboard/__init__.py", line 140, in update_dashboard
2015-04-09T10:56:17.69-0400 [App/0]      ERR     tweet_count = get_tweet_count()
2015-04-09T10:56:17.69-0400 [App/0]      ERR   File "/home/vcap/app/dashboard/__init__.py", line 208, in get_tweet_count
2015-04-09T10:56:17.69-0400 [App/0]      ERR     return int(r.get("stats:tweets")) #simple get from redis
2015-04-09T10:56:17.69-0400 [App/0]      ERR TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by mcowger** [comment]
Gotcha - I know where to fix this.

**Comment by vmtyler** [comment]
so do I. was trying to think of the cleanest way to deal with it. try?

**Comment by mcowger** [comment]
Yup - a `try/except` clause is the right way to handle this IM.
